export const dailyCategories = [
    "coffee orders",
    "mythical creatures",
    "flowers",
    "sports",
    "seafood",
    "female solo artists",
    "cocktails",
    "diseases",
    "marvel characters",
    "metals",
    "ivy league universities",
    "watch brands",
    "individual sports",
    "pizza toppings",
    "pancake toppings",
    "racquet sports",
    "types of tea",
    "musical instruments",
    "clothes",
    "video game consoles",
    "boy names under 7 letters",
    "girl names under 7 letters",
    "writing implements",
    "types of cheese",
    "types of pasta",
    "sports that don't involve a ball",
    "cities",
    "vegetables",
    "rooms in a house",
    "body parts",
    "disney princesses",
    "home furniture",
    "beach things",
    "writing implements",
    "marvel movies",
    "lunch food",
    "famous literature books",
    "toilet paper brands",
    "soda brands",
    "fast food chains",
    "salad ingredients",
    "high school classes",
    "planets",
    "synonyms for happy",
    "things found in a fridge",
    "conspiracy theories",
    "Mythological gods and goddesses",
    "Types of crystals and gemstones",
    "Famous art movements and styles",
    "Famous landmarks and geographical wonders",
    "Famous impostors and con artists",
    "Famous unsolved mysteries",
    "Types of pasta",
    "Types of candy",
    "Types of bread",
    "Types of birds",
]


export const validCategories = {
    animals: ['dog', 'cat', 'elephant', 'lion', 'tiger', 'bear', 'giraffe', 'gorilla', 'zebra', 'hippopotamus', 'kangaroo', 'rhinoceros', 'crocodile', 'gorilla', 'parrot', 'shark', 'bee', 'spider', 'owl', 'snake'],
    fruits: ['apple', 'banana', 'orange', 'strawberry', 'blueberry', 'raspberry', 'peach', 'plum', 'grape', 'mango', 'pineapple', 'watermelon', 'lime', 'lemon', 'kiwi', 'pomegranate', 'papaya', 'apricot', 'fig', 'avocado'],
    colors: ['red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink', 'black', 'white', 'gray', 'brown', 'beige', 'turquoise', 'gold', 'silver', 'bronze', 'navy', 'maroon', 'olive', 'lavender', 'teal'],
    cities: ['New York', 'London', 'Paris', 'Tokyo', 'Beijing', 'Sydney', 'Los Angeles', 'Chicago', 'Miami', 'Toronto', 'Moscow', 'Berlin', 'Madrid', 'Rome', 'Bangkok', 'Hong Kong', 'Istanbul', 'Rio de Janeiro', 'Mexico City', 'Shanghai'],
    food: ['pizza', 'pasta', 'sushi', 'tacos', 'hamburger', 'hot dog', 'sandwich', 'salad', 'soup', 'steak', 'chicken', 'fish', 'seafood', 'curry', 'ramen', 'dumplings', 'fried rice', 'pho', 'biryani', 'tandoori chicken'],
    clothing: ['shirt', 'dress', 'pants', 'jeans', 'jacket', 'coat', 'sweater', 'hoodie', 'T-shirt', 'blouse', 'skirt', 'shorts', 'leggings', 'jeggings', 'sweatpants', 'overalls', 'jumpsuit', 'romper', 'kimono', 'sari'],
    cars: ['Mercedes', 'BMW', 'Audi', 'Ford', 'Chevrolet', 'Honda', 'Toyota', 'Nissan', 'Porsche', 'Ferrari', 'Lamborghini', 'Bugatti', 'McLaren', 'Aston Martin', 'Tesla', 'Lexus', 'Dodge', 'Cadillac', 'Jeep', 'GMC', 'Buick'],
    flowers: ['rose', 'lily', 'daisy', 'sunflower', 'tulip', 'daffodil', 'carnation', 'iris', 'marigold', 'chrysanthemum', 'orchid', 'jasmine', 'lily of the valley', 'peony', 'lotus', 'hyacinth', 'azalea', 'hibiscus', 'anemone'],
    sports: ['soccer', 'basketball', 'football', 'tennis', 'golf', 'swimming', 'hockey', 'baseball', 'volleyball', 'cricket', 'rugby', 'boxing', 'skateboarding', 'snowboarding', 'surfing', 'cycling', 'running', 'yoga', 'pilates', 'weightlifting'],
    countries: ['United States', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'France', 'Germany', 'Italy', 'Spain', 'United Kingdom', 'Russia', 'China', 'Japan', 'South Korea', 'Australia', 'India', 'South Africa', 'Egypt', 'Morocco', 'Nigeria'],
    "things you find in the bedroom": ['bed', 'pillow', 'blanket', 'nightstand', 'lamp', 'dresser', 'mirror', 'wardrobe', 'chair', 'rug', 'alarm clock', 'books', 'photo frame', 'candles', 'plants', 'decorative pillows', 'curtains', 'window', 'fan', 'humidifier'],
    "rooms in a house": ['kitchen', 'living room', 'bedroom', 'bathroom', 'dining room', 'study', 'home office', 'basement', 'attic', 'garage', 'laundry room', 'mudroom', 'sunroom', 'guest room', 'playroom', 'media room', 'den', 'foyer', 'hallway', 'staircase'],
    "things you find in the kitchen": ['oven', 'refrigerator', 'microwave', 'dishwasher', 'sink', 'stove', 'kettle', 'toaster', 'blender', 'coffee maker', 'cutting board', 'knives', 'pots and pans', 'mixing bowls', 'utensils', 'plates', 'glasses', 'cups', 'baking sheet', 'spices'],
    "boy names": ['William', 'James', 'Alexander', 'Michael', 'Daniel', 'Matthew', 'David', 'Benjamin', 'Joseph', 'Jacob', 'Ethan', 'Noah', 'Andrew', 'Christopher', 'Anthony', 'Joshua', 'Nicholas', 'Ryan', 'Samuel', 'Tyler', 'Lucas'],
    "girl names": ['Emma', 'Olivia', 'Ava', 'Sophia', 'Isabella', 'Mia', 'Charlotte', 'Amelia', 'Harper', 'Evelyn', 'Abigail', 'Emily', 'Elizabeth', 'Sofia', 'Avery', 'Ella', 'Madison', 'Scarlett', 'Grace', 'Chloe', 'Victoria'],
    "Beach things": ["sunglasses", "beach towel", "beach umbrella", "flip flops", "sunscreen", "swimsuit", "beach bag", "coolers", "beach chair", "snorkeling gear", "beach ball", "frisbee"],
    "seafood": ["shrimp", "crab", "clams", "oysters", "lobster", "salmon", "tuna", "scallops", "mussels", "swordfish"],
    "breakfast food": ["pancakes", "waffles", "oatmeal", "fruit", "yogurt", "eggs", "bacon", "sausages", "bagels", "cereal", "smoothies", "muffins"],
    "lunch food": ["sandwiches", "wraps", "salads", "soups", "pizza", "burgers", "hot dogs", "tacos", "quesadillas", "sushi", "stir-fry", "pasta"],
    "body parts": ["arm", "leg", "hand", "foot", "head", "neck", "shoulder", "back", "chest", "abdomen", "thigh", "knee", "elbow", "wrist", "ankle"],
    "sports that don't involve a ball": ["swimming", "cycling", "boxing", "wrestling", "gymnastics", "track and field", "skateboarding", "surfing", "diving", "martial arts"],
    "common dog names": ["Max", "Buddy", "Charlie", "Lucy", "Daisy", "Molly", "Bailey", "Sadie", "Lola", "Maggie", "Stella", "Rocky", "Coco", "Roxy", "Chloe"],
    "common house pet animals": ["dog", "cat", "hamster", "rabbit", "guinea pig", "bird", "fish", "snake", "lizard", "turtle"],
    "writing implements": ["pen", "pencil", "marker", "highlighter", "chalk", "crayon", "ink", "quill", "brush", "stylus"],
    "home furniture": ["sofa", "armchair", "coffee table", "bookshelf", "bed", "wardrobe", "dining table", "desk", "dresser", "cabinet"],
    "cocktails": ["margarita", "mojito", "cosmopolitan", "martini", "daiquiri", "negroni", "manhattan", "screwdriver", "bloody mary", "mai tai"],
    "clothes": ["t-shirt", "jeans", "sweater", "dress", "skirt", "pants", "jacket", "hoodie", "blouse", "shorts", "socks", "shoes"],
    "Male solo singers": ["Elvis Presley", "Michael Jackson", "Frank Sinatra", "Prince", "David Bowie", "Freddie Mercury", "George Michael", "Stevie Wonder", "Phil Collins", "Robbie Williams"],
    "female solo artists": ["Beyoncé", "Adele", "Taylor Swift", "Ariana Grande", "Madonna", "Lady Gaga", "Whitney Houston", "Celine Dion", "Janet Jackson", "Mariah Carey"],
    "bands from the 1960s": ["The Beatles", "The Rolling Stones", "The Who", "The Beach Boys", "The Kinks", "The Doors", "The Byrds", "The Jimi Hendrix Experience", "The Supremes", "The Temptations"],
    "pancake toppings": ["maple syrup", "butter", "whipped cream", "strawberries", "blueberries", "raspberries", "bananas", "chocolate chips", "pecans", "coconut"],
    "diseases": ["cancer", "diabetes", "Alzheimer's disease", "Parkinson's disease", "heart disease", "stroke", "HIV/AIDS", "tuberculosis", "malaria", "Ebola"],
    "disney princesses": ["Snow White", "Cinderella", "Aurora", "Ariel", "Belle", "Jasmine", "Pocahontas", "Mulan", "Tiana", "Rapunzel", "Merida", "Moana"],
    "marvel movies": ["Iron Man", "Captain America: The First Avenger", "Thor", "The Avengers", "Guardians of the Galaxy", "Doctor Strange", "Spider-Man: Homecoming", "Black Panther", "Avengers: Infinity War", "Captain Marvel", "Avengers: Endgame"],
    "Christopher Nolan films": ["Memento", "Batman Begins", "The Prestige", "The Dark Knight", "Inception", "The Dark Knight Rises", "Interstellar", "Dunkirk", "Tenet"],
    "board games": ["Monopoly", "Scrabble", "Risk", "Catan", "Clue", "Ticket to Ride", "Chess", "Checkers", "Backgammon", "Battleship"],
    "most famous literature books": ["To Kill a Mockingbird", "The Great Gatsby", "Pride and Prejudice", "1984", "The Catcher in the Rye", "Brave New World", "The Lord of the Rings", "The Hobbit", "Harry Potter and the Philosopher's Stone", "The Chronicles of Narnia"],
    "presidents of the USA": ["George Washington", "Abraham Lincoln", "Franklin D. Roosevelt", "John F. Kennedy", "Barack Obama", "Donald Trump", "Joe Biden", "Thomas Jefferson", "Andrew Jackson", "Ronald Reagan"],
    "types of liquor": ["Whiskey", "Vodka", "Gin", "Rum", "Tequila", "Brandy", "Cognac", "Schnapps", "Absinthe", "Sake"],
    "Ivy league universities": ["Harvard University", "Yale University", "Princeton University", "Columbia University", "Cornell University", "Dartmouth College", "University of Pennsylvania", "Brown University"],
    "Metals": ["Gold", "Silver", "Copper", "Iron", "Aluminum", "Platinum", "Titanium", "Nickel", "Zinc", "Lead"],
    "toilet paper brands": ["Charmin", "Scott", "Cottonelle", "Angel Soft", "Quilted Northern", "Kleenex", "Puffs", "Seventh Generation", "Bounty", "Kirkland Signature"],
    "car brands": ["Toyota", "Ford", "Chevrolet", "Honda", "Nissan", "BMW", "Mercedes-Benz", "Audi", "Volvo", "Tesla"],
    "watch brands": ["Rolex", "Omega", "Breitling", "Tag Heuer", "Cartier", "Patek Philippe", "Tissot", "Casio", "Seiko", "Timex"],
    "individual sports": ["Swimming", "Track and Field", "Gymnastics", "Cycling", "Boxing", "Wrestling", "Weightlifting", "Tennis", "Golf", "Surfing"],
    "racquet sports": ["Tennis", "Badminton", "Squash", "Racquetball", "Ping Pong", "Pickleball"],
    "candy brands": ["Hershey's", "Mars", "Nestle", "Cadbury", "Ferrero", "Lindt", "Ghirardelli", "Godiva", "Tootsie Roll", "Skittles"],
    "computer brands": ["Apple", "Dell", "HP", "Lenovo", "Asus", "Acer", "MSI", "Alienware", "Microsoft", "Razer"],
    "dog breeds": ["Labrador Retriever", "German Shepherd", "Golden Retriever", "Bulldog", "Poodle", "Chihuahua", "Boxer", "Siberian Husky", "Beagle", "Dachshund"],
    "salad ingredients": ["Lettuce", "Tomatoes", "Cucumbers", "Carrots", "Bell Peppers", "Onions", "Mushrooms", "Olives", "Feta Cheese", "Croutons"],
    "pizza toppings": ["Pepperoni", "Mushrooms", "Onions", "Sausage", "Bacon", "Extra cheese", "Black olives", "Green peppers", "Pineapple", "Spinach", "Garlic", "Artichoke hearts"],
    "soda brands": ["Coca-Cola", "Pepsi", "Sprite", "Dr. Pepper", "Mountain Dew", "Fanta", "7Up", "A&W Root Beer", "Canada Dry", "Schweppes"],
    "fast food chains": ["McDonald's", "Burger King", "Wendy's", "KFC", "Subway", "Taco Bell", "Pizza Hut", "Domino's", "Papa John's", "Chick-fil-A", "Hardee's", "Carl's Jr."],
    "high school class subjects": ["Algebra", "Biology", "Chemistry", "English Literature", "Geography", "History", "Physical Education", "Physics", "Spanish", "French", "Art"],
    "video game consoles": ["PlayStation 5", "Xbox Series X", "Nintendo Switch", "PlayStation 4", "Xbox One", "Wii U", "PlayStation 3", "Xbox 360", "Wii", "PlayStation 2", "Xbox"],
    "famous actors": ["Tom Hanks", "Leonardo DiCaprio", "Meryl Streep", "Denzel Washington", "Robert De Niro", "Julia Roberts", "Brad Pitt", "Angelina Jolie", "Will Smith", "Emma Stone", "Johnny Depp", "Scarlett Johansson"],
    "coffee orders": ["Espresso", "Americano", "Latte", "Cappuccino", "Mocha", "Flat White", "Macchiato", "Iced Coffee", "Frappuccino", "Turkish Coffee", "Irish Coffee"],
    "types of tea": ["Black tea", "Green tea", "White tea", "Oolong tea", "Herbal tea", "Chai tea", "Earl Grey tea", "Jasmine tea", "Peppermint tea", "Ginger tea", "Lemon tea"],
    "aquatic animals": ["Dolphin", "Whale", "Shark", "Octopus", "Jellyfish", "Sea turtle", "Crab", "Lobster", "Seahorse", "Clam", "Starfish", "Eel"],
    "planets": ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"],
    "emotions": ["happiness", "anger", "sadness", "fear", "disgust", "surprise", "joy", "love"],
    "things found in a fridge": ["milk", "cheese", "eggs", "vegetables", "fruit", "leftovers", "condiments"],
    "types of footwear": ["sneakers", "boots", "sandals", "loafers", "heels", "flats", "slippers"],
    "synonyms for happy": ["joyful", "ecstatic", "content", "pleased", "delighted", "elated", "overjoyed"],
    "musical instruments": ["piano", "guitar", "violin", "drums", "saxophone", "trumpet", "flute", "cello"],
    "Fictional species from movies and TV shows": ["Hobbits", "Wookiees", "Na'vi", "Vulcans", "Ewoks", "Klingons", "Daleks"],
    "Phobias": ["Arachnophobia", "Claustrophobia", "Acrophobia", "Agoraphobia", "Nyctophobia", "Ophidiophobia", "Thanatophobia"],
    "conspiracy theories": ["Moon landing was fake", "9/11 was an inside job", "Elvis is still alive", "Flat earth theory", "Chemtrails"],
    "Words that sound like they're made up but are actually real": ["Gobbledygook", "Brouhaha", "Hocus-pocus", "Mumbo jumbo", "Flummox"],
    "Things you wouldn't want to find in your fast food": ["Hair", "Rodent Droppings", "Insects"],
    "Famous explorers throughout history": ["Christopher Columbus", "Marco Polo", "Vasco da Gama"],
    "Traditional dances from different countries": ["Tango (Argentina)", "Salsa (Latin America)", "Hula (Hawaii)"],
    "Famous landmarks around the world": ["Taj Mahal", "Eiffel Tower", "Colosseum"],
    "Mythological gods and goddesses": ["Zeus", "Hera", "Aphrodite"],
    "Famous art movements and styles": ["Impressionism", "Cubism", "Expressionism"],
    "Types of crystals and gemstones": ["Quartz", "Amber", "Jade"],
    "Strange and unusual fruits": ["Ackee", "Dragon Fruit", "Rambutan"],
    "Inventions that changed the world": ["Light Bulb", "Wheel", "Printing Press"], 
    "Mythical creatures from folklore": ["Unicorn", "Kraken", "Loch Ness Monster"],
    "Famous unsolved mysteries": ["Jack the Ripper", "Bermuda Triangle", "D.B. Cooper"],
    "Famous impostors and con artists": ["Frank Abagnale", "Karl Pelz", "Rachel Dolezal"],
    "Famous painters": ["Vincent Van Gogh", "Rembrandt", "Pablo Picasso"],
    "Types of pasta": ["Spaghetti", "Penne", "Fusilli"],
    "Types of trees": ["Oak", "Maple", "Cedar"],
    "Types of cheese": ["Cheddar", "Gouda", "Swiss"],
    "Types of fish": ["Salmon", "Tuna", "Tilapia"],
    "Types of birds": ["Hawk", "Duck", "Flamingo"],
    "Types of flowers": ["Roses", "Daisies", "Lilies", "Tulips", "Poppies", "Orchids", "Carnations", "Hyacinths", "Snapdragons", "Chrysanthemums"],
    "Types of clouds": ["Cumulus", "Cirrus", "Stratocumulus", "Altostratus", "Cumulonimbus", "Altocumulus", "Nimbostratus", "Stratiformis", "Cirrostratus", "Cirrocumulus"],
    "Types of candy": ["Gummy Bears", "M & Ms", "Licorice", "Sour Patch Kids", "Gum Drops", "Chocolate Bars", "Jelly Beans", "Lollipops", "Taffy", "Skittles"],
    "Types of bread": ["White", "Whole Wheat", "Sourdough", "Rye", "Multigrain", "Pumpernickel", "Ciabatta", "Baguette", "Focaccia", "English Muffin"],
}